ignore:
  - "diagnoser/gui/widgets.mock.go"
  - "examples"

coverage:
  range: 50..90
  round: up
  status:
    project:
      default:
        #        target: 70%
        #        threshold: 20%
        if_not_found: success
        if_ci_failed: success
    patch:
      default:
        target: 0%
        threshold: 20%
        if_no_uploads: success
        if_not_found: success
        if_ci_failed: success
