// Code generated by MockGen. DO NOT EDIT.
// Source: ./diagnoser/diagnoser.go

// Package diagnoser is a generated GoMock package.
package diagnoser

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockGUI is a mock of GUI interface
type MockGUI struct {
	ctrl     *gomock.Controller
	recorder *MockGUIMockRecorder
}

// MockGUIMockRecorder is the mock recorder for MockGUI
type MockGUIMockRecorder struct {
	mock *MockGUI
}

// NewMockGUI creates a new mock instance
func NewMockGUI(ctrl *gomock.Controller) *MockGUI {
	mock := &MockGUI{ctrl: ctrl}
	mock.recorder = &MockGUIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGUI) EXPECT() *MockGUIMockRecorder {
	return m.recorder
}

// Run mocks base method
func (m *MockGUI) Run(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run
func (mr *MockGUIMockRecorder) Run(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockGUI)(nil).Run), arg0)
}

// MockDiagnoser is a mock of Diagnoser interface
type MockDiagnoser struct {
	ctrl     *gomock.Controller
	recorder *MockDiagnoserMockRecorder
}

// MockDiagnoserMockRecorder is the mock recorder for MockDiagnoser
type MockDiagnoserMockRecorder struct {
	mock *MockDiagnoser
}

// NewMockDiagnoser creates a new mock instance
func NewMockDiagnoser(ctrl *gomock.Controller) *MockDiagnoser {
	mock := &MockDiagnoser{ctrl: ctrl}
	mock.recorder = &MockDiagnoserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDiagnoser) EXPECT() *MockDiagnoserMockRecorder {
	return m.recorder
}

// Run mocks base method
func (m *MockDiagnoser) Run() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run
func (mr *MockDiagnoserMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockDiagnoser)(nil).Run))
}
